server:
   port: 8060
publisher:
   kafka:
      topic: content-timestamp-topic
spring:
   kafka:
      bootstrap-servers: host.docker.internal:9092
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
         properties:
            spring:
               json:
                  trusted:
                     packages: com.falcon.publisher