version: '3'
services:
   zookeeper:
      container_name: zookeper-ctr
      image: wurstmeister/zookeeper
      ports:
      - "2181:2181"            
   kafka:
      container_name: kafka-ctr
      image: wurstmeister/kafka
      depends_on:
      - zookeeper
      ports:
      - "9092:9092"
      environment:
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_LISTENERS: INSIDE://kafka:9090,OUTSIDE://:9092
         KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9090,OUTSIDE://host.docker.internal:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT         
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE         
         KAFKA_CREATE_TOPICS: "content-timestamp-topic:1:1"   
   persister-service:
      container_name: persister-service-ctr
      image: persister-service:latest      
      build:
         context: persister
         dockerfile: Dockerfile
      ports:
      - 18700:8070
      depends_on:
      - kafka
   broadcaster-service:
      container_name: broadcaster-service-ctr
      image: broadcaster-service:latest
      build:
         context: broadcaster
         dockerfile: Dockerfile
      ports:
      - 18900:8090      
      depends_on:
      - kafka
   publisher-service:
      container_name: publisher-service-ctr
      image: publisher-service:latest
      build:
         context: publisher
         dockerfile: Dockerfile
      ports:
      - 18600:8060
      depends_on:
      - persister-service
      - broadcaster-service