server:
   port: 8070
persister:
   kafka:
      topic: content-timestamp-topic
spring:
   kafka:
      bootstrap-servers: host.docker.internal:9092
      consumer:
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         properties:
            spring:
               json:
                  trusted:
                     packages: com.falcon.persister
   datasource:      
      initialization-mode: always
      url: jdbc:h2:mem:falconDB
      driverClassName: org.h2.Driver
      username: sa
      password: 
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: none
   h2:
      console:
         enabled: true
         path: /h2-console
         settings:
            trace: false
            web-allow-others: true