DROP TABLE IF EXISTS TBL_DATA;

DROP SEQUENCE IF EXISTS SEQ_TBL_DATA;

CREATE SEQUENCE SEQ_TBL_DATA START WITH 100 INCREMENT BY 5;

SELECT SEQ_TBL_DATA.NEXTVAL FROM DUAL;

CREATE TABLE TBL_DATA (
	MESSAGE_ID INT PRIMARY KEY,
	CONTENT VARCHAR(1000),
	MESSAGE_TS TIMESTAMP WITH TIME ZONE,
	ROW_CREATED_TS TIMESTAMP WITH TIME ZONE,
	LAST_UPDATED_TS TIMESTAMP WITH TIME ZONE
);


INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (1,'alpha',TO_TIMESTAMP('2019-10-05 13:03:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (2,'bravo',TO_TIMESTAMP('2020-06-06 06:00:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (3,'charlie',TO_TIMESTAMP('2020-10-07 17:01:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (4,'Abrakadaarbraa',TO_TIMESTAMP('2020-10-08 04:12:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (5,'delta',TO_TIMESTAMP('2021-05-04 21:02:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
INSERT INTO TBL_DATA (MESSAGE_ID,CONTENT,MESSAGE_TS,ROW_CREATED_TS,LAST_UPDATED_TS) VALUES (6,'abccba',TO_TIMESTAMP('2021-05-12 18:00:12+0530','yyyy-mm-dd HH:MM:ssZ'),SYSTIMESTAMP,SYSTIMESTAMP);
